### ISSUE TITLE
Integrate Aniseed macros as part of grammar

### ISSUE THREAD

**Issue by katawful** [TravonteD/tree-sitter-fennel#33]
[Aniseed](https://github.com/Olical/aniseed) is a compilation environment for Fennel for NeoVim that introduces a number of useful Clojure-like macros for Fennel. Currently the parser just recognizes these are raw macros, but since these macros are meant to replace and enhance features of Fennel, and since they also cannot be redefined by those using Aniseed, it might be a smart idea to include them in the grammar so they can be parsed appropriately. [This](https://github.com/Olical/aniseed/blob/9c8f2cd17d454a38b11cedd323579b579ee27f9c/doc/aniseed.txt#L49) Is a list of the current macros, but the following is a rough example:

```clojure
; module header macro to export and import values
(module module-name
  {autoload {autoload some.file}
   require {require some.file}
   require-macros [require.some.macro.file]})
; defn replaces fn, is exported with the module
(defn function [] (print :x))
(fn function [] (print :x))

; def defines some module local value that can be exported
; it is scoped like local and behaves mostly the same, but exports easier
(def value "value")
```
There's more to these, but as you can see these macros can become quite useful when working in an Aniseed environment, so it would be useful if some of these could be added.

**Comment by TravonteD** [comment]
Hi, firstly thanks for bringing up the idea! I'd rather not have special logic for something that's not in core fennel since this parser is used in other editors, however, I believe this can be achieved by providing custom queries to nvim-treesitter (This requires more investigation). In which case, the aniseed maintainers could provide them along with their macros.
